sonar.projectKey=02franek_ebiznes

sonar.organization=02franek

sonar.projectName=Ebiznes Zadanie 7

sonar.sources=ebiznes/zadanie_5/client,ebiznes/zadanie_5/server

sonar.sources=ebiznes/zadanie_5/client
