sonar.projectKey=02franek_ebiznes
sonar.organization=02franek


sonar.sources=zadanie_5/client/src,zadanie_5/server
sonar.exclusions=**/node_modules/**,zadanie_5/client/dist/**
sonar.language=go,ts,tsx,js,jsx
