name: CI Pipeline Zadanie 10

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-backend:
    name: Build Go Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zadanie_5/server

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Configure Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Download dependencies
        run: go mod tidy

      - name: Run Go tests
        run: go test -v ./...

      - name: Building binary
        run: go build -o api-server main.go

  build-frontend:
    name: Build React Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zadanie_5/client

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Configure Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build static app
        run: npm run build

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan code
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy to AWS
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            if [[ ! -d "ebiznes" ]]; then
              git clone https://github.com/02franek/ebiznes.git ebiznes
            fi

            cd ebiznes
            git checkout main
            git pull origin main
            cd zadanie_5

            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose-prod.yml up -d --build
